import express from "express";
import cors from "cors";
import accountTypeRoutes from "./routes/AccountTypeRoutes";
import currencyRoutes from "./routes/CurrencyRoutes";
import accountRoutes from "./routes/AccountRoutes";
import chartOfAccountRoutes from "./routes/AuxiliarySystemRoutes";
import accountingEntryRoutes from "./routes/AccountingEntryRoutes";
import authRoutes from "./routes/AuthRoutes";
import { authenticationMiddleware } from "./middlewares/authentication.middleware";
const app = express();
const API_PREFIX = "/api/v1";
app.use(cors());
app.use(express.json());
app.use(`${API_PREFIX}/auth`, authRoutes);
app.use(authenticationMiddleware);
app.use(`${API_PREFIX}/accounts`, accountRoutes);
app.use(`${API_PREFIX}/currencies`, currencyRoutes);
app.use(`${API_PREFIX}/account-types`, accountTypeRoutes);
app.use(`${API_PREFIX}/auxiliary-systems`, chartOfAccountRoutes);
app.use(`${API_PREFIX}/accounting-entries`, accountingEntryRoutes);

export default app;
